services:
  # consul:
  #   image: "consul:1.15.4"
  #   ports:
  #     - "8500:8500"

  mysql:
    image: "mysql:latest"
    container_name: url_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=url_db
      - "TZ=Asia/Shanghai"
    # volumes:
      # - ./db/init:docker-entrypoint-initdb.d
    restart: always

  # postgres:
  #   image: postgres
  #   container_name: postgres_urls
  #   environment:
  #     - POSTGRES_USER=root
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=urldb
  #   ports:
  #     - "5432:5432"
  #   restart: always

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

      